Curs5/proiect/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    #path('', views.CreateJobView.as_view(), name='adaugare'),
    path('create/',views.CreateJobView.as_view(), name='adaugare'),
    path('update/<int:pk>', views.UpdateJobView.as_view(), name='modificare'),
    path('list/', views.ListJobView.as_view(), name='listare'),
    path('delete/<int:pk>/', views.delete_job, name='remove'),
]

Curs5/proiect/proiect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('jobs.urls')),
]

Curs5/proiect/jobs/models.py
from django.db import models
from aplicatie2.models import Companies

# Create your models here.

class Job(models.Model):

    name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    description = models.TextField()
    customer = models.ForeignKey('aplicatie2.Companies', on_delete=models.CASCADE)
    active = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.name} {self.url} {self.description} {self.customer} {self.active}"

# se realizeaza Create, Read, Update, Delete (CRUD) pentru modulul de jobs.
# trebuie sa avem o validare in care sa nu existe job cu nume si customer identic

Curs5/proiect/jobs/forms.py
from django import forms
from jobs.models import Job

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'

    def __init__(self, pk, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)
        self.aux_pk = pk

    def clean(self):
        cleaned_data = self.cleaned_data
        name_value = cleaned_data.get('name')
        customer_value = cleaned_data.get('customer')
        if self.aux_pk:
            if Job.objects.filter(name__icontains=name_value, customer=customer_value).exclude(id=self.aux_pk).exists():
                self._errors['name'] = self.error_class(["JObul exista deja la aceasta companie"])
        else:
            if Job.objects.filter(name__icontains=name_value, customer=customer_value).exists():
                self._errors['name'] = self.error_class(["JObul exista deja la aceasta companie"])
        return cleaned_data

Curs5/proiect/jobs/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from jobs.forms import JobForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect


from jobs.models import Job
# Create your views here.

class CreateJobView(LoginRequiredMixin, CreateView):
    model = Job
    #fields='__all__'
    form_class = JobForm
    template_name = 'jobs/jobs_form.html'

    def get_form_kwargs(self):
        variable_to_send = super(CreateJobView, self).get_form_kwargs()
        variable_to_send.update({'pk': None})
        return variable_to_send

    def get_success_url(self):
        return reverse('jobs:adaugare')

class UpdateJobView(LoginRequiredMixin, UpdateView):
    model = Job
    #fields = '__all__'
    form_class = JobForm
    template_name = 'jobs/jobs_form.html'

    def get_form_kwargs(self):
        variable_to_send = super(UpdateJobView, self).get_form_kwargs()
        variable_to_send.update({'pk':self.kwargs['pk']})
        return variable_to_send

    def get_success_url(self):
        return reverse('jobs:adaugare')

class ListJobView(LoginRequiredMixin, ListView):
    model = Job
    template_name = 'jobs/jobs_index.html'

    def get_queryset(self):
        return Job.objects.filter(active=1)

@login_required
def delete_job(request, pk):
    if request.user.is_authenticated:
        Job.objects.filter(id=pk).update(active=0)
    return redirect('jobs:listare')

Curs5/proiect/templates/jobs/jobs_form.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .errorlist {
            color: red
        }
    </style>
    <form method="POST">
        {% csrf_token %}
        {% for item in form %}
            {{ item.label }} {{ item }}<br>
            {{ item.errors }}
        {% endfor %}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Curs5/proiect/templates/jobs/jobs_index.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .update_button{
            width: 10%;
            background-color: blue;
            color: yellow;
            text-decoration: none;
            border: red;
        }
        .remove_button{
            width: 10%;
            background-color: red;
            color: black;
            text-decoration: none;
            border: black;
        }
        table > thead > tr > th{
            width: 200px;
        }
    </style>
    <a class="add_button" href="{% url 'jobs:adaugare' %}">Add new job</a>
    <table>
        <thead>
            <tr>
                <th>Index</th>
                <th>Name</th>
                <th>Url</th>
                <th>Description</th>
                <th>Customer</th>
            </tr>
        </thead>
        <tbody>
            {% for item in job_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.name|upper }}</td>
                    <td>{{ item.url }}</td> <br>
                    <td>{{ item.description }}</td>
                    <td>{{ item.customer }}</td>
                    <td><a class="update_button" href="{% url 'jobs:modificare' item.id %}">Update job</a></td>
                    <td><a class="remove_button" href="{% url 'jobs:remove' item.id %}">Remove job</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}