Curs5/proiect/aplicatie1/urls.py
from django.urls import path
from aplicatie1 import views


app_name = 'aplicatie1'

urlpatterns = [
    path('', views.CreateLocationView.as_view(), name='adaugare'),
    path('<int:pk>/update', views.UpdateLocationView.as_view(), name='modificare'),
    path('list/', views.ListLocationView.as_view(), name='listare'),
    path('delete/<int:pk>/', views.delete_location, name='remove'),
]

Curs5/proiect/aplicatie2/urls.py
from django.urls import path
from aplicatie2 import views

app_name = 'aplicatie2'

urlpatterns = [
    path('new_timesheet', views.newPontaj, name='pontaj'),
    path('stop_timesheet', views.stopTimesheet, name='oprire_pontaj'),
    path('add/', views.CreateCompaniesView.as_view(), name='adaugare'),
    path('edit<int:pk>', views.UpdateCompaniesView.as_view(), name='modificare'),
    path('index/', views.ListCompaniesView.as_view(), name='lista'),
    path('profile/<int:pk>/', views.UpdateProfile.as_view(), name='update_profile'),
    path('new_account/', views.NewAccountView.as_view(), name='adauga_utilizator'),

]

Curs5/proiect/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    #path('', views.CreateJobView.as_view(), name='adaugare'),
    path('create/',views.CreateJobView.as_view(), name='adaugare'),
    path('update/<int:pk>', views.UpdateJobView.as_view(), name='modificare'),
    path('list/', views.ListJobView.as_view(), name='listare'),
    path('delete/<int:pk>/', views.delete_job, name='remove'),
]

Curs5/proiect/proiect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('jobs.urls')),
]

Curs5/proiect/templates/base.html
<html>
    <head>
        <title>Proiect DJANGO</title>
    </head>
    <body>
        <nav>
            <div>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'aplicatie1:listare' %}">Location</a>
                    <a href="{% url 'aplicatie2:lista' %}">Company</a>
                    <a href="{% url 'jobs:listare' %}">Jobs</a>
                    <a href="{% url 'aplicatie2:update_profile' request.user.id %}">User profile</a>
                    <a href="{% url 'aplicatie2:adauga_utilizator' %}">New user</a>
                    <a href="{% url 'jobs:adaugare' %}">New job</a>
                    {% if ready_to_work is False %}
                         <a href="{% url 'aplicatie2:oprire_pontaj' %}">Oprire pontaj</a>
                    {% else %}
                        <a href="{% url 'aplicatie2:pontaj' %}">Pornire pontaj</a>
                    {% endif %}
                    <a href="{% url 'logout' %}">Logout</a>
                {% endif %}
            </div>
        </nav>
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>