Curs5/proiect/aplicatie1/urls.py
from django.urls import path
from aplicatie1 import views


app_name = 'aplicatie1'

urlpatterns = [
    path('', views.CreateLocationView.as_view(), name='adaugare'),
    path('<int:pk>/update', views.UpdateLocationView.as_view(), name='modificare'),
    path('list/', views.ListLocationView.as_view(), name='listare'),
    path('delete/<int:pk>/', views.delete_location, name='remove'),
]

Curs5/proiect/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    #path('', views.CreateJobView.as_view(), name='adaugare'),
    path('create/',views.CreateJobView.as_view(), name='adaugare'),
    path('update/<int:pk>', views.UpdateJobView.as_view(), name='modificare'),
    path('list/', views.ListJobView.as_view(), name='listare'),
    path('delete/<int:pk>/', views.delete_job, name='remove'),
]

Curs5/proiect/proiect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('jobs.urls')),
]

Curs5/proiect/aplicatie1/models.py
from django.db import models

# Create your models here.


class Location(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    active = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.city} {self.country}"

Curs5/proiect/aplicatie1/forms.py
from django import forms
from aplicatie1.models import Location

class LocationForm(forms.ModelForm):
        class Meta:
                model = Location
                fields = ['city', 'country']  #nu trebuie neaparat lista, merge si set

        def __init__(self, pk, *args, **kwargs):
                super(LocationForm, self).__init__(*args, **kwargs)
                self.pk = pk

        def clean(self):
                cleaned_data = self.cleaned_data
                city_value = cleaned_data.get('city')
                country_value = cleaned_data.get('country')
                if self.pk:
                        if Location.objects.filter(city__icontains=city_value, country__icontains=country_value).exclude(id=self.pk).exists():
                                self._errors['city'] = self.error_class(["Orasul si tare deja exists"])
                else:
                        if Location.objects.filter(city__icontains=city_value, country__icontains=country_value).exists():
                                self._errors['city'] = self.error_class(["Orasul si tare deja exists"])
                return cleaned_data

Curs5/proiect/aplicatie1/views.py
# Create your views here.
# CreateView -> clasa pt adaugat date in formular
# UpdateView -> clasa pt modificat date in formular
# DeleteView -> clasa pt sters date din formular
# IndexView -> clasa pt informat cu privire la formular
# ListView -> clasa pt informatii de tip lista din db
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView
from aplicatie1.models import Location
from django.contrib.auth.decorators import login_required
from aplicatie1.forms import LocationForm

class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Location
    #fields = '__all__'
    #fields = ['city', 'country']
    form_class = LocationForm
    template_name = 'aplicatie1/location_form.html'

    def get_success_url(self):
        return reverse('aplicatie1:listare')

    def get_form_kwargs(self):
        data = super(CreateLocationView, self).get_form_kwargs()
        data.update({'pk': None})
        return data


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    # fields = '__all__'
    #fields = ['city', 'country']
    form_class = LocationForm
    template_name = 'aplicatie1/location_form.html'

    def get_forms_kwargs(self):
        data = super(UpdateLocationView, self).get_form_kwargs()
        data.update({'pk': self.kwargs['pk']})
        return data

    def get_success_url(self):
        return reverse('aplicatie1:listare')


class ListLocationView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'aplicatie1/location_index.html'

    def get_queryset(self):
        return Location.objects.filter(active=1)

@login_required
def delete_location(request, pk):
    if request.user.is_authenticated:
        Location.objects.filter(id=pk).update(active=0)
    return redirect('aplicatie1:listare')

Curs5/proiect/templates/aplicatie1/location_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Curs5/proiect/templates/aplicatie1/location_index.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .add_button {
            width: 10%;
            background-color: yellow;
            color: blue;
            text-decoration: none;
            border: 1px solid green;
        }
        .update_button{
            width: 10%;
            background-color: blue;
            color: yellow;
            text-decoration: none;
            border: red;
        }
        .remove_button{
            width: 10%;
            background-color: red;
            color: black;
            text-decoration: none;
            border: black;
        }
        table > thead > tr {
            background-color: gray;
        }
        table > thead > tr > th{
            width: 20%;
        }
    </style>
    <br><br><br>
    <a class="add_button" href="{% url 'aplicatie1:adaugare' %}">Add new location</a>
    <table>
        <thead>
            <tr>
                <th>Index</th>
                <th>City</th>
                <th>Country</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for item in location_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.city|upper }}</td>
                <td>{{ item.country }}</td>
                <td><a class="update_button" href="{% url 'aplicatie1:modificare' item.id %}">Update location</a></td>
                <td><a class="remove_button" href="{% url 'aplicatie1:remove' item.id %}">Remove location</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}